const btnTheme = {
  sizes: {
    auto: {
      p: "0.25rem 1rem",
      w: "auto",
      h: "fit-content",
      bg: "primary.type7",
      fontFamily: "main",
      fontStyle: "normal",
      fontSize: "md",
      color: "font.inverse",
      borderRadius: "base",
      _hover: {
        bgColor: "primary.type8",
      },
    },
    page: {
      fontSize: "1.2rem",
      p: 0,
      w: "2rem",
      h: "2rem",
    },
  },
  variants: {
    cancel: {
      bg: "red",
    },
    subMenu: {
      p: "0",
      display: "inline-flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      gap: "0.25rem",
      lineHeight: "1.125rem",
      fontFamily: "main",
      fontSize: "xs",
      fontStyle: "normal",
      fontWeight: "regular",
      color: "font.primary",
      bgColor: "transparent",
      _active: {
        fontWeight: "strong",
        div: {
          bg: "linear-gradient(180deg, #D4B106 0%, rgba(212, 177, 6, 0) 100%)",
        },
        svg: {
          color: "#FFFFFF",
        },
      },
      _hover: {
        bgColor: "transparent",
        fontWeight: "strong",
        div: {
          bg: "linear-gradient(180deg, #D4B106 0%, rgba(212, 177, 6, 0) 100%)",
        },
        svg: {
          color: "#FFFFFF",
        },
      },
    },
    inputElement: {
      bgColor: "primary.main.bg",
      borderRadius: "base",
      color: "primary.main.font",
      lineHeight: 1.5,
      transition: "0.3s",
      _hover: {
        bgColor: "primary.main.hover",
      },
    },
    pagenation: {
      display: "flex",
      flexWrap: "wrap",
      alignItems: "center",
      minW: "17.75px",
      w: "auto",
      h: "18.48px",
      borderRadius: "pagenation",
      border: "1px solid",
      borderColor: "transparent",
      fontFamily: "main",
      fontSize: "xs",
      fontWeight: "medium",
      lineHeight: "18.48px",
      color: "font.primary",
      transition: "0.3s",
      _hover: {
        color: "primary.type7",
      },
      _active: {
        cursor: "initial",
        color: "primary.type7",
        borderColor: "primary.type7",
      },
    },
    search: {
      p: "0 0.4375rem",
      w: "auto",
      h: "1.375rem",
      gap: "0.625rem",
      fontSize: "xs",
      fontWeight: "medium",
      lineHeight: "1.375rem",
    },
    linkBtn: {
      p: "0",
      bg: "transparent",
      fontSize: "sm",
      color: "primary.type7",
    },
    upload: {
      display: "flex",
      flexDirection: "row",
      p: "5px 16px",
      gap: "8px",
      w: "148px",
      h: "32px",
      bgColor: "bg.primary",
      border: "1px solid",
      borderColor: "border.input",
      boxShadow: "0px 2px 0px rgba(0, 0, 0, 0.016)",
      borderRadius: "base",
      flex: "none",
      order: 0,
      flexGrow: 0,
      fontFamily: "main",
      fontStyle: "normal",
      fontWeight: "medium",
      fontSize: "sm",
      lineHeight: "1.375rem",
      color: "#000000D9",
      _hover: {
        color: "#FFFFFF",
        svg: {
          color: "#FFFFFF",
          borderColor: "transparent",
        },
      },
    },
    historyAdd: {
      display: "flex",
      flexDirection: "row",
      p: "5px 16px",
      gap: "8px",
      w: "148px",
      h: "32px",
      bgColor: "primary.type7",
      border: "1px solid",
      borderColor: "primary.type7",
      borderRadius: "base",
      flex: "none",
      order: 0,
      flexGrow: 0,
      fontFamily: "main",
      fontStyle: "normal",
      fontWeight: "medium",
      fontSize: "sm",
      lineHeight: "1.5",
      color: "#FFFFFF",
      _hover: {
        color: "#FFFFFF",
        svg: {
          bgColor: "primary.type8",
          borderColor: "primary.type8",
          color: "#FFFFFF",
        },
      },
    },
    addrBtn: {
      background: "#FFFFFF",
      px: "0.5rem",
      w: "100%",
      h: "1.5rem",
      justifyContent: "flex-start",
      border: "1px solid",
      borderColor: "border.input",
      fontSize: "0.8125rem",
      fontWeight: "regular",
      lineheight: "1.5rem",
      color: "font.primary",
      _hover: {
        color: "font.inverse",
      },
    },
    filterTop: {
      p: 0,
      bg: "none",
      flexDirection: "column",
      justifyContent: "center",
      gap: "0.25rem",
      fontWeight: "regular",
      fontSize: "xs",
      lineHeight: "1.0625rem",
      color: "font.primary",
      div: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        w: "2.5rem",
        h: "2.5rem",
        boxSizing: "border-box",
        borderRadius: "70px",
        backdropFilter: "blur(5px)",
        bg: "linear-gradient(180deg, #FFFFFF 0%, rgba(255, 255, 255, 0) 100%)",
        filter: "drop-shadow(0px 0px 4px rgba(0, 0, 0, 0.25))",
      },
      _active: {
        bg: "none",
        fontWeight: "strong",
        div: {
          bgColor: "primary.type7",
        },
      },
      _hover: {
        bg: "none",
        fontWeight: "strong",
        div: {
          bgColor: "primary.type7",
        },
      },
    },
    filterTopMain: {
      bg: "none",
      // fontFamily: 'Inter';
      fontWeight: "strong",
      fontSize: "xs",
      lineHeight: "1",
      color: "font.secondary",
      textShadow: "0px 6.4px 6.4px rgba(0, 0, 0, 0.25)",
      _active: {
        bg: "none",
        div: {
          bgColor: "primary.type7",
        },
      },
      _hover: {
        bg: "none",
        div: {
          bgColor: "primary.type7",
        },
      },
    },
    backBtn: {
      position: "absolute",
      top: 0,
      left: "-3rem",
      zIndex: 1,
      gap: "4px",
      bg: "none",
      // fontFamily: 'Vox',
      fontWeight: "strong",
      fontSize: "0.6875rem",
      lineHeight: "0.9375rem",
      p: {
        p: "0 2px",
        bg: "font.title",
        color: "font.inverse",
      },
      svg: {
        color: "font.title",
      },
      _active: {
        bg: "none",
      },
      _hover: {
        bg: "none",
      },
    },
    slctArea: {
      w: "100%",
      h: "1.75rem",
      bgColor: "neutral.gray1",
      border: "1px solid",
      borderColor: "neutral.gray6",
      borderRadius: "base",
      fontWeight: "strong",
      fontSize: "0.6875rem",
      lineHeight: 1,
      color: "font.secondary",
      _hover: {
        bgColor: "primary.type7",
        color: "#EDEDED",
      },
    },
  },
  defaultProps: {
    size: "auto",
  },
};

export { btnTheme };
