const themeLink = {
  baseStyle: {
    fontFamily: "main",
    fontStyle: "normal",
    color: "font.primary",
    textDecoration: "none",
    outline: "none",
    lineHeight: "normal",
    _hover: {
      fontWeight: "strong",
      textDecoration: "none",
    },
  },
  sizes: {},
  variants: {
    serviceLink: {
      fontSize: "sm",
      fontWeight: "regular",
      lineHeight: "1.375rem",
      color: "font.placeholder",
      transition: "0.1s",
    },
    headMenuOff: {
      position: "relative",
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: "0.75rem",
      h: "100%",
      textStyle: "header.menu",
      color: "font.placeholder",
      transition: "all 0.3s",
      _hover: {
        fontWeight: "strong",
        color: "primary.type7",
        svg: { color: "primary.type7" },
        _after: {
          position: "absolute",
          top: 0,
          left: 0,
          content: "attr(data-text)",
          w: "100%",
          h: "100%",
          borderBottom: "2px solid",
          borderColor: "primary.type7",
          fontSize: 0,
          color: "transparent",
        },
      },
    },
    headMenuOn: {
      position: "relative",
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: "0.75rem",
      h: "100%",
      textStyle: "header.menu",
      color: "primary.type7",
      transition: "all 0.3s",
      _after: {
        position: "absolute",
        top: 0,
        left: 0,
        content: "attr(data-text)",
        w: "100%",
        h: "100%",
        borderBottom: "2px solid",
        borderColor: "primary.type7",
        fontSize: 0,
        color: "transparent",
      },
      _hover: {
        fontWeight: "strong",
      },
    },
  },
  defaultProps: {},
};

export default themeLink;
